import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const sceneEl=document.querySelector('#scene'),scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x05070b,.032);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,500);camera.position.set(0,3.8,8);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;sceneEl.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x8aa2bd,0x020306,1.1));const moon=new THREE.DirectionalLight(0xaac4ff,2.4);moon.position.set(-8,12,4);moon.castShadow=true;scene.add(moon);
const headLight=new THREE.SpotLight(0xdfffff,55,38,.28,.45,1.2);headLight.position.set(0,2.2,1.2);scene.add(headLight);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(300,300),new THREE.MeshStandardMaterial({color:0x0a0e12,roughness:.48,metalness:.18}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const roadMat=new THREE.MeshStandardMaterial({color:0x151a1e,roughness:.85});for(let i=-2;i<=2;i++){const r=new THREE.Mesh(new THREE.PlaneGeometry(3.8,300),roadMat);r.rotation.x=-Math.PI/2;r.position.x=i*4.7;r.position.y=.008;scene.add(r)}
const bike=new THREE.Group();scene.add(bike);function wheel(z){const g=new THREE.Group();const t=new THREE.Mesh(new THREE.TorusGeometry(.55,.16,14,28),new THREE.MeshStandardMaterial({color:0x070809,roughness:.9}));t.rotation.y=Math.PI/2;t.castShadow=true;g.add(t);const h=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,.18,16),new THREE.MeshStandardMaterial({color:0x8b949e,metalness:.8,roughness:.25}));h.rotation.z=Math.PI/2;g.add(h);g.position.z=z;return g}
const rear=wheel(.82),front=wheel(-.82);rear.position.y=.62;front.position.y=.62;bike.add(rear,front);
const frame=new THREE.Mesh(new THREE.BoxGeometry(.42,.16,1.25),new THREE.MeshStandardMaterial({color:0x9dbb28,metalness:.55,roughness:.28}));frame.position.y=1.18;frame.rotation.x=-.08;bike.add(frame);
const seat=new THREE.Mesh(new THREE.BoxGeometry(.5,.12,.78),new THREE.MeshStandardMaterial({color:0x15181b,roughness:.45}));seat.position.set(.15,1.48,.2);seat.rotation.x=-.05;bike.add(seat);
const tank=new THREE.Mesh(new THREE.SphereGeometry(.36,16,10),new THREE.MeshStandardMaterial({color:0x26321a,metalness:.35,roughness:.35}));tank.scale.set(.9,.7,1.25);tank.position.set(0,1.46,-.12);bike.add(tank);
const engine=new THREE.Mesh(new THREE.BoxGeometry(.45,.48,.48),new THREE.MeshStandardMaterial({color:0x747b80,metalness:.8,roughness:.25}));engine.position.set(0,1.03,.05);bike.add(engine);
const fork=new THREE.Mesh(new THREE.BoxGeometry(.08,.9,.08),new THREE.MeshStandardMaterial({color:0xb7c0c8,metalness:.9,roughness:.2}));fork.position.set(0,1.15,-.72);fork.rotation.x=-.18;bike.add(fork);
const bar=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.72,10),new THREE.MeshStandardMaterial({color:0x141619,metalness:.6}));bar.rotation.z=Math.PI/2;bar.position.set(0,1.76,-.82);bike.add(bar);
const lamp=new THREE.Mesh(new THREE.CylinderGeometry(.2,.22,.08,16),new THREE.MeshStandardMaterial({color:0xeaffff,emissive:0xcfffff,emissiveIntensity:5}));lamp.rotation.x=Math.PI/2;lamp.position.set(0,1.62,-.87);bike.add(lamp);
bike.scale.set(1.05,1.05,1.05);bike.position.set(0,0,.5);
const rainCount=2200,rainGeo=new THREE.BufferGeometry(),rainPos=new Float32Array(rainCount*3);for(let i=0;i<rainCount;i++){rainPos[i*3]=(Math.random()-.5)*80;rainPos[i*3+1]=Math.random()*28;rainPos[i*3+2]=(Math.random()-.5)*80}rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0x9db7d4,size:.035,transparent:true,opacity:.6}));scene.add(rain);
const markers=[{id:'about',x:-9,z:-13},{id:'work',x:9,z:-31},{id:'skills',x:-10,z:-50},{id:'contact',x:10,z:-69}];
for(const m of markers){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,2.2,8),new THREE.MeshStandardMaterial({color:0xd7ff3f,emissive:0x4a6610,emissiveIntensity:2}));pole.position.set(m.x,1.1,m.z);scene.add(pole);const orb=new THREE.Mesh(new THREE.SphereGeometry(.16,12,12),new THREE.MeshStandardMaterial({color:0xd7ff3f,emissive:0xd7ff3f,emissiveIntensity:4}));orb.position.set(m.x,2.25,m.z);scene.add(orb)}
const keys={};addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let dragging=false,lastX=0;renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX});addEventListener('pointerup',()=>dragging=false);addEventListener('pointermove',e=>{if(dragging){heading-=(e.clientX-lastX)*.004;lastX=e.clientX}});
function openPanel(id){document.querySelectorAll('.content-panel').forEach(x=>x.classList.add('hidden-panel'));document.getElementById(id)?.classList.remove('hidden-panel')}
document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.target)));document.querySelectorAll('.close-panel').forEach(b=>b.addEventListener('click',()=>b.parentElement.classList.add('hidden-panel')));
let soundOn=false;document.querySelector('#sound').onclick=()=>{soundOn=!soundOn;document.querySelector('#sound').textContent=soundOn?'SOUND ON':'SOUND OFF'};
let speed=0,heading=0;const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),forward=keys.w||keys.arrowup,back=keys.s||keys.arrowdown,left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright;if(forward)speed=Math.min(speed+dt*5,7);else if(back)speed=Math.max(speed-dt*6,-2);else speed*=Math.pow(.05,dt);if(left)heading+=dt*1.7*(.4+Math.abs(speed)/4);if(right)heading-=dt*1.7*(.4+Math.abs(speed)/4);bike.position.x+=Math.sin(heading)*speed*dt;bike.position.z+=Math.cos(heading)*speed*dt;bike.position.x=Math.max(-14,Math.min(14,bike.position.x));bike.rotation.y=heading;bike.rotation.z=THREE.MathUtils.lerp(bike.rotation.z,(right?-.13:left?.13:0),.08);front.rotation.x+=speed*dt*1.2;rear.rotation.x+=speed*dt*1.2;camera.position.lerp(new THREE.Vector3(bike.position.x-Math.sin(heading)*7,3.2,bike.position.z-Math.cos(heading)*7),.055);camera.lookAt(bike.position.x,bike.position.y+1,bike.position.z-2);rain.position.z=bike.position.z;const p=rainGeo.attributes.position.array;for(let i=1;i<p.length;i+=3){p[i]-=dt*18;if(p[i]<0)p[i]=28}rainGeo.attributes.position.needsUpdate=true;let closest=0,dist=Infinity;markers.forEach((m,i)=>{const d=Math.hypot(bike.position.x-m.x,bike.position.z-m.z);if(d<dist){dist=d;closest=i}});document.querySelector('#location-title').textContent=dist<8?markers[closest].id.toUpperCase():'THE TRAILHEAD';document.querySelector('#location-sub').textContent=dist<8?'TAP THE MARKER TO EXPLORE':'PRATIK POUDEL / PORTFOLIO';renderer.render(scene,camera)}animate();setTimeout(()=>document.body.classList.add('loaded'),900);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});