'use client';
import { VscGithub,VscMail,VscLinkExternal } from 'react-icons/vsc'; import Link from 'next/link'; import styles from '@/styles/AboutPage.module.css';
const AboutPage=()=> <div className={styles.page}><div className={styles.container}>
<header className={styles.header}><div className={styles.headerContent}><div className={styles.headerText}><h1 className={styles.name}>Pratik Poudel</h1><p className={styles.role}>BSc (Hons) Information Technology — Computer Systems Engineering</p><div className={styles.location}><span className={styles.dot}/>Butwal, Nepal</div></div></div><div className={styles.headerActions}><a href="https://github.com/pyatrick666" target="_blank" rel="noopener noreferrer" className={styles.iconButton}><VscGithub size={20}/></a><Link href="/contact" className={styles.iconButton}><VscMail size={20}/></Link></div></header>
<div className={styles.content}>
<section className={styles.section}><div className={styles.sectionHeader}><span className={styles.sectionNumber}>01</span><h2 className={styles.sectionTitle}>About</h2></div><div className={styles.sectionBody}><p className={styles.paragraph}>I&apos;m Pratik Poudel, a bachelor&apos;s running student studying Information Technology with a focus on Computer Systems Engineering. I enjoy turning what I learn into practical software and technology projects.</p><p className={styles.paragraph}>I&apos;m interested in full-stack development, networking and general software development opportunities where I can learn from real projects and contribute useful work.</p></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><span className={styles.sectionNumber}>02</span><h2 className={styles.sectionTitle}>Education</h2></div><div className={styles.sectionBody}><div className={styles.experienceCard}><div className={styles.expMeta}><span className={styles.expPeriod}>2025 — Present</span></div><h3 className={styles.expRole}>BSc (Hons) Information Technology — Computer Systems Engineering</h3><p className={styles.expCompany}>ISMT College, Nepal · University of Sunderland</p><ul className={styles.expList}><li>Expected graduation: 2028</li><li>Software development, computer systems and enterprise project focus</li></ul></div><div className={styles.experienceCard}><div className={styles.expMeta}><span className={styles.expPeriod}>2021</span></div><h3 className={styles.expRole}>+2 Computer Science</h3><p className={styles.expCompany}>New Horizon College, Drive-tole, Butwal</p></div></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><span className={styles.sectionNumber}>03</span><h2 className={styles.sectionTitle}>Skills</h2></div><div className={styles.sectionBody}><div className={styles.skillsGrid}>
<div className={styles.skillCategory}><h4 className={styles.skillTitle}>Languages</h4><div className={styles.skillTags}>{['JavaScript','TypeScript','Java','Dart','SQL','C#','Python','PHP'].map(x=><span className={styles.skillTag} key={x}>{x}</span>)}</div></div>
<div className={styles.skillCategory}><h4 className={styles.skillTitle}>Development</h4><div className={styles.skillTags}>{['React','Next.js','Flutter','Web Development','Mobile App Development'].map(x=><span className={styles.skillTag} key={x}>{x}</span>)}</div></div>
<div className={styles.skillCategory}><h4 className={styles.skillTitle}>Design</h4><div className={styles.skillTags}>{['Figma','Canva','UI/UX Design'].map(x=><span className={styles.skillTag} key={x}>{x}</span>)}</div></div>
<div className={styles.skillCategory}><h4 className={styles.skillTitle}>Tools</h4><div className={styles.skillTags}>{['Git','GitHub','Linux'].map(x=><span className={styles.skillTag} key={x}>{x}</span>)}</div></div>
</div></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><span className={styles.sectionNumber}>04</span><h2 className={styles.sectionTitle}>Coursework</h2></div><div className={styles.sectionBody}><p className={styles.paragraph}>Relevant coursework includes:</p><div className={styles.writingLinks}>{['Object-Oriented Programming','Web Development','Database Systems','Software Engineering','Computer Systems','Enterprise Project'].map(x=><span key={x} className={styles.writingLink}><span>{x}</span><VscLinkExternal size={14}/></span>)}</div></div></section>
<section className={styles.section}><div className={styles.sectionHeader}><span className={styles.sectionNumber}>05</span><h2 className={styles.sectionTitle}>Current Focus</h2></div><div className={styles.sectionBody}><p className={styles.paragraph}>I&apos;m currently looking for internship opportunities in networking, full-stack development and general software development while continuing to build practical projects.</p></div></section>
</div><footer className={styles.footer}><Link href="/projects" className={styles.footerLink}>View my projects →</Link></footer></div></div>;
export default AboutPage;