import React,{useEffect,useRef}from'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,Mail,Menu,X,Code2,Smartphone,Network,Palette,Database,ExternalLink}from'lucide-react';import{gsap}from'gsap';import'./styles.css';

const skills=[['Software Development','React, TypeScript, JavaScript, Java, C#, Python, C','code'],['Full-Stack Development','HTML, CSS, Bootstrap, Node.js, Express, PHP, Django','code'],['Mobile Development','Flutter, Dart, Firebase','phone'],['Computer Systems','Linux, Networking, Cisco, Raspberry Pi','network'],['Data & Backend','MySQL, PostgreSQL, APIs, Cloud Services','database'],['Design','Figma, Canva, UI/UX, responsive interfaces','palette']];
const projects=[{name:'ChessMate',type:'Mobile Application',desc:'A Flutter chess application with polished gameplay, AdMob monetisation and an online multiplayer direction.',tags:['Flutter','Dart','Firebase','AdMob'],href:'https://pyatrick666.itch.io/chessmate'},{name:'ePortfolio',type:'Web Portfolio',desc:'A responsive developer ePortfolio covering web technologies, projects, skills and interactive demonstrations.',tags:['HTML','CSS','JavaScript','Bootstrap'],href:'https://pyatrick666.github.io/ePortfolio/'},{name:'Professional Portfolio',type:'Personal Project',desc:'This portfolio: a responsive React and TypeScript experience designed to present software, systems and design work.',tags:['React','TypeScript','GSAP','CSS'] ,href:'https://github.com/pyatrick666/Professional-Portfolio'}];

function App(){const[open,setOpen]=React.useState(false);const navRef=useRef<HTMLElement>(null);useEffect(()=>{const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;gsap.fromTo('.reveal',{y:28,opacity:0},{y:0,opacity:1,duration:.8,stagger:.08,ease:'power3.out'});gsap.to('.orb',{y:-22,rotation:8,duration:4,repeat:-1,yoyo:true,ease:'sine.inOut'});},[]);useEffect(()=>{const close=(e:MouseEvent)=>{if(open&&navRef.current&&!navRef.current.contains(e.target as Node)&&!(e.target as HTMLElement).closest('.menu'))setOpen(false)};document.addEventListener('click',close);return()=>document.removeEventListener('click',close)},[open]);return <div className="site">
<div className="ambient" aria-hidden="true"><span className="orb orb1"/><span className="orb orb2"/><span className="gridGlow"/></div>
<header><a className="logo" href="#home" aria-label="Pratik Poudel home">PP<span>.</span></a><nav ref={navRef} className={open?'open':''} aria-label="Primary navigation">{['home','about','skills','projects','contact'].map(x=><a key={x} href={'#'+x} onClick={()=>setOpen(false)}>{x}</a>)}</nav><div className="head-actions"><a className="icon" href="https://github.com/pyatrick666" target="_blank" rel="noopener noreferrer" aria-label="Open Pratik Poudel on GitHub"><span className="brand-mark">GH</span></a><button className="menu" type="button" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="primary-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
<main>
<section id="home" className="hero" aria-labelledby="hero-title"><div className="hero-copy reveal"><p className="eyebrow">SOFTWARE • SYSTEMS • DIGITAL EXPERIENCES</p><h1 id="hero-title">Pratik<br/><em>Poudel.</em></h1><p className="lead">IT student and developer building practical software, full-stack experiences and computer-system solutions.</p><div className="buttons"><a className="btn primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a><a className="btn ghost" href="mailto:pyatrick666@gmail.com">Let's connect <Mail size={17}/></a></div></div><div className="hero-card reveal"><div className="terminal" aria-label="Profile summary"><div className="dots" aria-hidden="true"><i/><i/><i/></div><p><span>$</span> whoami</p><h3>Pratik Poudel</h3><p><span>+</span> BSc (Hons) Information Technology</p><p><span>+</span> Computer Systems Engineering</p><p><span>+</span> ISMT College · University of Sunderland</p><p><span>+</span> Building & learning every day_</p></div></div></section>
<section id="about" className="section" aria-labelledby="about-title"><div className="section-head reveal"><p className="eyebrow">01 / ABOUT</p><h2 id="about-title">Building with curiosity,<br/><span>shipping with purpose.</span></h2></div><div className="about-grid"><div className="about-text reveal"><p>I’m Pratik Poudel, a BSc (Hons) Information Technology student specialising in Computer Systems Engineering at ISMT College, affiliated with the University of Sunderland.</p><p>My interests sit at the intersection of software development, full-stack engineering, mobile apps, networking and interface design. I enjoy taking an idea from a rough concept to something people can actually use.</p><p>I’m currently focused on growing through practical projects, coursework and internship opportunities across software, full-stack development and networking.</p></div><div className="facts reveal"><div><b>2025—2028</b><span>Degree journey</span></div><div><b>Flutter</b><span>Mobile development</span></div><div><b>React</b><span>Web development</span></div><div><b>Linux</b><span>Systems & networking</span></div></div></div></section>
<section id="skills" className="section" aria-labelledby="skills-title"><div className="section-head reveal"><p className="eyebrow">02 / TOOLKIT</p><h2 id="skills-title">Things I <span>work with.</span></h2></div><div className="skill-grid">{skills.map(([a,b,c])=><article className="skill reveal" key={a}><div className="skill-icon" aria-hidden="true">{c==='phone'?<Smartphone/>:c==='network'?<Network/>:c==='database'?<Database/>:c==='palette'?<Palette/>:<Code2/>}</div><h3>{a}</h3><p>{b}</p></article>)}</div></section>
<section id="projects" className="section projects" aria-labelledby="projects-title"><div className="section-head reveal"><p className="eyebrow">03 / SELECTED WORK</p><h2 id="projects-title">Projects worth <span>exploring.</span></h2><p className="sub">A mix of portfolio work, independent builds and practical coursework.</p></div><div className="project-grid">{projects.map((p,i)=><a className="project reveal" href={p.href} target="_blank" rel="noopener noreferrer" aria-label={'Open '+p.name+' project'} key={p.name}><div className="project-no" aria-hidden="true">0{i+1}</div><div><p className="project-type">{p.type}</p><h3>{p.name}</h3><p>{p.desc}</p><div className="tags" aria-label="Technologies used">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><ExternalLink aria-hidden="true"/></a>)}</div></section>
<section id="contact" className="contact section" aria-labelledby="contact-title"><div className="contact-box reveal"><p className="eyebrow">04 / CONTACT</p><h2 id="contact-title">Have a project,<br/><span>opportunity or idea?</span></h2><p>I'm open to internships, collaborative projects and conversations about software, full-stack development and computer systems.</p><a className="btn primary" href="mailto:pyatrick666@gmail.com">Email me <Mail size={17}/></a><div className="socials"><a href="https://github.com/pyatrick666" target="_blank" rel="noopener noreferrer"><span className="brand-mark">GH</span> GitHub</a><a href="https://www.linkedin.com/in/pratik-poudel-b3264a263/" target="_blank" rel="noopener noreferrer"><span className="brand-mark">in</span> LinkedIn</a></div></div></section>
</main><footer><span>© {new Date().getFullYear()} Pratik Poudel</span><span>Designed & built with React · TypeScript · GSAP</span><a href="#home" aria-label="Back to top"><ArrowUpRight aria-hidden="true"/></a></footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);